version: '3.8'

services:
  medical-records-service:
    build: .
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
